modLoader="javafml"
loaderVersion="[32,)"
license="All Rights Reserved."
issueTrackerURL="https://github.com/Giant-Salted-Fish/Key-Binding-Patch/issues"
showAsResourcePack=false

[[mods]]
	modId="key_binding_patch"
	version="1.0.0"
	displayName="Key Binding Patch"
	updateJSONURL="https://raw.githubusercontent.com/Giant-Salted-Fish/Key-Binding-Patch/1.16.X/update.json"
	displayURL=""
	logoFile="logo.png"
	credits="All code contributors."
	authors="Giant_Salted_Fish"
	description='''
Patches the vanilla Key binding system to support better key combinations and resolve conflicts.
	'''

[[dependencies.key_binding_patch]]
	modId="forge"
	mandatory=true
	versionRange="[36,)"
	ordering="NONE"
	side="CLIENT"

[[dependencies.key_binding_patch]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.16.3,1.17)"
	ordering="NONE"
	side="CLIENT"
