modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"
issueTrackerURL="https://github.com/Giant-Salted-Fish/Key-Binding-Patch/issues"
showAsResourcePack=false

[[mods]]
	modId="key_binding_patch"
	version="${file.jarVersion}"
	displayName="Key Binding Patch"
	updateJSONURL="https://raw.githubusercontent.com/Giant-Salted-Fish/Key-Binding-Patch/1.16.X/update.json"
	displayURL="https://www.mcmod.cn/class/12624.html"
	logoFile="logo.png"
	credits="All code contributors."
	authors="Giant_Salted_Fish"
	description='''
Patches the vanilla Key binding system to support better key combinations and resolve conflicts.
'''

[[dependencies.key_binding_patch]]
	modId="forge"
	mandatory=true
	versionRange="[40,)"
	ordering="NONE"
	side="CLIENT"

[[dependencies.key_binding_patch]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.18.2,1.19)"
	ordering="NONE"
	side="CLIENT"
