modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/Giant-Salted-Fish/Key-Binding-Patch/issues"

[[mods]]
	modId="${mod_id}"
	version="${mod_version}"
	displayName="${mod_name}"
	updateJSONURL="https://raw.githubusercontent.com/Giant-Salted-Fish/Key-Binding-Patch/1.16.X/update.json"
	displayURL="https://www.mcmod.cn/class/12624.html"
	logoFile="logo.png"
	credits="All code contributors."
	authors="${mod_authors}"
	description='''${mod_description}'''
	displayTest="NONE"


[[dependencies.${mod_id}]]
	modId="forge"
	mandatory=true
	versionRange="${forge_version_range}"
	ordering="NONE"
	side="CLIENT"

# Here's another dependency
[[dependencies.${mod_id}]]
	modId="minecraft"
	mandatory=true
	versionRange="${minecraft_version_range}"
	ordering="NONE"
	side="CLIENT"
